### PR TITLE
Content to content inclusion

### PR DESCRIPTION
**Pull request by ebrehault**
## Principle
The previous PR #43 allows on-the-fly content modification.
With this PR, instead of inserting hard-coded HTML, we have a new tag `<include />` able to retrive a piece of content from the document itself retrieved. For instance:
```xml
 <before css:content-children="#main">
    <include css:content="#breadcrumbs" />
</before>
```
The `<include />` tag accepts a `href` attribute, so it can retrieve a piece of content from another page. For instance:
```xml
<after css:content="#main">
    <include css:content="form" href="contact.html" />
</after>
```

## Implementation
As discussed in #42, the `include ` tag is just a simpler syntax for:
```xml
<xsl:apply-templates select="..." mode="raw"/>
```

@lrowe I have fork it from the my #43 branch before merging with the Python 3 changes (as they broke the tests).

### CODE REVIEW

**Comment by djay** [comment]
So this replaces #43 ?
I think it looks cleaner. Still a little bit confusing because

``` 
<before css:theme-children="#main">
    <include css:content="#breadcrumbs" />
</before>
```
and 

```
<before css:theme-children="#main" css:content="#breadcrumbs" />
```

are the same right?

Also, would this also be able to be extended to something like the subtemplates idea?

```
<replace css:theme-children="#portlets" css:content=".ploneportlet">
    <include css:theme="#sampleportlet">
       <replace theme="./th" content="./div[0]"/>
       <replace css:theme=".description" css:content=",plonedescription"/>
    </include>
</replace>
```

Where the include is pulling in a html from the theme file as a sub mockup/theme and the inner replace can use that as its context to make finer grain replacements?

**Comment by ebrehault** [comment]
No, that's #43 + #44 which replace #42 (by the way, I gonna close that one).

And no, `include` cannot be used in a theme rule, so:
```xml
<before css:theme-children="#main">
    <include css:content="#breadcrumbs" />
</before>
```
would not work (and I guess we should report an error, that's not the case at the moment).

And regarding the templating, it is a very different issue, it cannot be implemented the way this PR has been implemented.

**Comment by djay** [comment]
Is it possible to make it work? otherwise its even more confusing. Why can you use include only in a content before and not a theme before?

Another question, can you include multiple include statements?

**Comment by ebrehault** [comment]
That's fixed (and rebased), so now `include` can be used in theme rules too.
And yes, multiple include does work.

**Comment by lrowe** [comment]
With the #43 changes merged to master, I've rebased the relevant commit in the `include-content-review` branch. I think we (probably me) needs to do a bit more work before merging this as I'd like to ensure we remove codepaths so that:

We first normalize the rule:
```
<before css:theme-children="#main" css:content="#breadcrumbs" />
```
to:
```
<before css:theme-children="#main">
    <include css:content="#breadcrumbs" />
</before>
```

And we extend support for esi/ssi includes to the include rule processing.

**Comment by ebrehault** [comment]
@lrowe do you think we could merge this PR and implement the 2 features you mentionned (normalizing rules using `include` and extend ESI/SSI support) later?
(No pressure here, I am just asking, as the content inclusion mechanism is very handy, I would like to release it as soon as possible, but obviously I do want to do it if you think the implementation is not ready for merging yet)

**Comment by lrowe** [comment]
@ebrehault sorry I'm being slow about this, I'm swamped at the moment and no longer use diazo myself so finding time/energy to work on it is hard.

I'm reluctant to merge as is because I think normalizing the two rule types together is important for ensuring their equivalency.

Do feel free to take a shot at finishing up though.

**Comment by ebrehault** [comment]
Ok, good, I will work on it.

**Comment by ebrehault** [comment]
@lrowe just to let you know, I plan to work on it this weekend at the conference sprint and try to merge it

**Comment by ebrehault** [comment]
Now erbased and imporved in #49

**Pull request closed without merging**
