### PR TITLE
use anchor_safe_urljoin for xlink:href attributes

### PR DESCRIPTION
**Pull request by huubbouma**
Please consider my pull request. We encountered an issue in our current project, and these changes fix the issue.

### CODE REVIEW

**Comment by davilima6** [comment]
I think @lrowe would be a better person to review this.

**Comment by huubbouma** [comment]
Hi @davilima6 
I don't know what the normal procedure is for a pull request like this. I can merge the pull request myself, but it seems better to me that someone else has a look at it first. Since you seem to be the latest one pushing to this repository I thought I'd add you as assignee.

**Comment by davilima6** [comment]
Lgtm. I ran the 5.0 and 5.1 Jenkins jobs and there was one failure in each but I think they're unrelated.

**Comment by lrowe** [comment]
Looks good to me. Could you please rebase on master so we can get Travis to run the tests for this PR.

**Comment by huubbouma** [comment]
I rebased. local test run seems fine now

**Pull request merged**
